-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 12:27:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ejemplo_producto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ejemplo_producto` ;

-- -----------------------------------------------------
-- Schema ejemplo_producto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejemplo_producto` ;
USE `ejemplo_producto` ;

-- -----------------------------------------------------
-- Table `ejemplo_producto`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`CLIENTE` (
  `dni` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `telefono` VARCHAR(11) NULL,
  PRIMARY KEY (`dni`, `nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`PROVEEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`PROVEEDOR` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`PROVEEDOR` (
  `nlf` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `dirección` TEXT(60) NOT NULL,
  `PROVEEDORcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nlf`, `nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`PRODUCTO` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'ninguno',
  `precio` FLOAT NOT NULL,
  `PROVEEDOR_nlf` INT NOT NULL,
  `PROVEEDOR_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_PRODUCTO_PROVEEDOR1_idx` (`PROVEEDOR_nlf` ASC, `PROVEEDOR_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_nlf` , `PROVEEDOR_nombre`)
    REFERENCES `ejemplo_producto`.`PROVEEDOR` (`nlf` , `nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`CLIENTE_has_PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`CLIENTE_has_PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`CLIENTE_has_PRODUCTO` (
  `CLIENTE_dni` INT NOT NULL,
  `CLIENTE_nombre` VARCHAR(45) NOT NULL,
  `PRODUCTO_codigo` INT NOT NULL,
  PRIMARY KEY (`CLIENTE_dni`, `CLIENTE_nombre`, `PRODUCTO_codigo`),
  INDEX `fk_CLIENTE_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_codigo` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_PRODUCTO_CLIENTE_idx` (`CLIENTE_dni` ASC, `CLIENTE_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO_CLIENTE`
    FOREIGN KEY (`CLIENTE_dni` , `CLIENTE_nombre`)
    REFERENCES `ejemplo_producto`.`CLIENTE` (`dni` , `nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_codigo`)
    REFERENCES `ejemplo_producto`.`PRODUCTO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
